// app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavigationBar } from "@/components/navbar/navigation-bar";
import { ThemeProvider } from "@/components/themeprovider";

const jetBrainsMono = localFont({
  src: [
    { path: './fonts/JetBrainsMono-Thin.woff2', weight: '100' },
    { path: './fonts/JetBrainsMono-Regular.woff2', weight: '400' },
    { path: './fonts/JetBrainsMono-Bold.woff2', weight: '700' },
  ],
  variable: '--font-jetbrains-mono',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <body
        className={`${jetBrainsMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Scrollable Container */}
          <div className="h-screen w-full overflow-auto bg-[url('/bg.png')] bg-cover bg-center">
            {/* Inner Container */}
            <div className="flex flex-col relative w-full">
              {/* Navigation Bar */}
              <NavigationBar />

              {/* Main Content */}
              <main className="flex-1">
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
